"""initial migration

Revision ID: 7f384f6a7b51
Revises: 
Create Date: 2026-01-17 09:57:33.043615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f384f6a7b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_crontab_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.String(length=200), nullable=True, comment='分钟'),
    sa.Column('hour', sa.String(length=200), nullable=True, comment='小时'),
    sa.Column('day_of_week', sa.String(length=200), nullable=True, comment='日期'),
    sa.Column('day_of_month', sa.String(length=200), nullable=True, comment='月份'),
    sa.Column('month_of_year', sa.String(length=200), nullable=True, comment='年'),
    sa.Column('timezone', sa.String(length=200), nullable=True, comment='时区'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('celery_interval_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('every', sa.Integer(), nullable=True, comment='区间数'),
    sa.Column('period', sa.String(length=24), nullable=True, comment='间隔单位'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('celery_periodic_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True, comment='定时任务名'),
    sa.Column('task', sa.String(length=200), nullable=True, comment='任务路径'),
    sa.Column('args', sa.String(length=200), nullable=True, comment='参数'),
    sa.Column('kwargs', sa.String(length=200), nullable=True, comment='关键字参数'),
    sa.Column('queue', sa.String(length=200), nullable=True, comment='队列'),
    sa.Column('exchange', sa.String(length=200), nullable=True, comment='交换'),
    sa.Column('routing_key', sa.String(length=200), nullable=True, comment='路由密钥'),
    sa.Column('expires', sa.DateTime(), nullable=True, comment='到期时间'),
    sa.Column('one_off', sa.Boolean(), nullable=True, comment='执行一次'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('enabled', sa.String(length=200), nullable=True, comment='是否启用, 1启动，0停用'),
    sa.Column('last_run_at', sa.String(length=200), nullable=True, comment='上次运行时间'),
    sa.Column('total_run_count', sa.String(length=200), nullable=True, comment='运行总次数'),
    sa.Column('date_changed', sa.DateTime(), nullable=True, comment='更改日期'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('crontab_id', sa.Integer(), nullable=True, comment='定时器id'),
    sa.Column('crontab', sa.Integer(), nullable=True, comment='crontab 表达式'),
    sa.Column('interval_id', sa.Integer(), nullable=True, comment='间隔id'),
    sa.Column('interval_every', sa.Integer(), nullable=True, comment='间隔时间'),
    sa.Column('interval_period', sa.String(length=24), nullable=True, comment='间隔类型'),
    sa.Column('task_type', sa.String(length=255), nullable=False, comment='crontab interval'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目id'),
    sa.Column('module_id', sa.Integer(), nullable=False, comment='模块id'),
    sa.Column('suite_id', sa.Integer(), nullable=False, comment='套件id'),
    sa.Column('case_env_id', sa.Integer(), nullable=False, comment='case_env_id 用例环境'),
    sa.Column('case_ids', sa.String(length=255), nullable=False, comment='用例集合'),
    sa.Column('ui_env_id', sa.Integer(), nullable=False, comment='case_env_id 用例环境'),
    sa.Column('ui_ids', sa.String(length=255), nullable=False, comment='ui用例集合'),
    sa.Column('script_ids', sa.String(length=255), nullable=False, comment='脚本id'),
    sa.Column('task_tags', sa.String(length=255), nullable=False, comment='任务标签'),
    sa.Column('remarks', sa.String(length=255), nullable=False, comment='任务描述'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('celery_periodic_task_changed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True, comment='到期时间'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('file_info',
    sa.Column('id', sa.String(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='存储的文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('extend_name', sa.String(length=255), nullable=True, comment='扩展名称'),
    sa.Column('original_name', sa.String(length=255), nullable=True, comment='原名称'),
    sa.Column('content_type', sa.String(length=255), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.String(length=255), nullable=True, comment='文件大小'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_file_info_extend_name'), 'file_info', ['extend_name'], unique=False)
    op.create_table('lookup',
    sa.Column('code', sa.String(length=64), nullable=False, comment='编码'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_lookup_code'), 'lookup', ['code'], unique=False)
    op.create_table('lookup_value',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('lookup_id', sa.Integer(), nullable=False, comment='所属类型'),
    sa.Column('lookup_code', sa.String(length=32), nullable=False, comment='编码'),
    sa.Column('lookup_value', sa.String(length=256), nullable=True, comment='值'),
    sa.Column('ext', sa.String(length=256), nullable=True, comment='拓展1'),
    sa.Column('display_sequence', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_lookup_value_lookup_code'), 'lookup_value', ['lookup_code'], unique=False)
    op.create_index(op.f('ix_lookup_value_lookup_id'), 'lookup_value', ['lookup_id'], unique=False)
    op.create_table('menu',
    sa.Column('path', sa.String(length=255), nullable=False, comment='菜单路径'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='菜单名称'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件路径'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='title'),
    sa.Column('isLink', sa.Integer(), nullable=True, comment='开启外链条件，`1、isLink: true 2、链接地址不为空（meta.isLink） 3、isIframe: false`'),
    sa.Column('isHide', sa.Integer(), nullable=True, comment='菜单是否隐藏（菜单不显示在界面，但可以进行跳转）'),
    sa.Column('isKeepAlive', sa.Integer(), nullable=True, comment='菜单是否缓存'),
    sa.Column('isAffix', sa.Integer(), nullable=True, comment='固定标签'),
    sa.Column('isIframe', sa.Integer(), nullable=True, comment='是否内嵌'),
    sa.Column('roles', sa.String(length=64), nullable=True, comment='权限'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='icon'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级菜单id'),
    sa.Column('redirect', sa.String(length=255), nullable=True, comment='重定向路由'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('menu_type', sa.Integer(), nullable=True, comment='菜单类型'),
    sa.Column('lookup_id', sa.Integer(), nullable=True, comment='数据字典'),
    sa.Column('active_menu', sa.String(length=255), nullable=True, comment='显示页签'),
    sa.Column('views', sa.Integer(), nullable=True, comment='访问数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_menu_icon'), 'menu', ['icon'], unique=False)
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=False)
    op.create_index(op.f('ix_menu_title'), 'menu', ['title'], unique=False)
    op.create_table('menu_view_history',
    sa.Column('menu_id', sa.Integer(), nullable=True, comment='菜单id'),
    sa.Column('remote_addr', sa.String(length=64), nullable=True, comment='访问ip'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='访问人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_menu_view_history_menu_id'), 'menu_view_history', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_view_history_remote_addr'), 'menu_view_history', ['remote_addr'], unique=False)
    op.create_index(op.f('ix_menu_view_history_user_id'), 'menu_view_history', ['user_id'], unique=False)
    op.create_table('module_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='模块ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模块名称'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='模块描述'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('notify',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('group', sa.String(length=64), nullable=True, comment='组'),
    sa.Column('message', sa.String(length=500), nullable=True, comment='消息'),
    sa.Column('send_status', sa.Integer(), nullable=True, comment='发送状态，10成功 20 失败'),
    sa.Column('read_status', sa.Integer(), nullable=True, comment='消息状态，10未读 20 已读'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_notify_user_id'), 'notify', ['user_id'], unique=False)
    op.create_table('project_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('remote_addr', sa.String(length=255), nullable=False, comment='用户名称'),
    sa.Column('real_ip', sa.String(length=255), nullable=False, comment='用户名称'),
    sa.Column('request', sa.Text(), nullable=False, comment='用户名称'),
    sa.Column('method', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('args', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('form', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('json', sa.Text(), nullable=True, comment='操作'),
    sa.Column('response', sa.Text(), nullable=True, comment='操作'),
    sa.Column('endpoint', sa.Text(), nullable=True, comment='操作'),
    sa.Column('elapsed', sa.Text(), nullable=True, comment='操作'),
    sa.Column('request_time', sa.DateTime(), nullable=True, comment='操作'),
    sa.Column('env', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('employee_code', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('toekn', sa.String(length=255), nullable=True, comment='操作'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=True, comment='菜单名称'),
    sa.Column('role_type', sa.Integer(), nullable=False, comment='权限类型，10菜单权限，20用户组权限'),
    sa.Column('menus', sa.String(length=64), nullable=True, comment='菜单列表'),
    sa.Column('description', sa.Integer(), nullable=True, comment='描述'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 10 启用 20 禁用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_roles_menus'), 'roles', ['menus'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_role_type'), 'roles', ['role_type'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password', sa.Text(), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('roles', sa.JSON(), nullable=False, comment='用户类型'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户状态  1 锁定， 0 正常'),
    sa.Column('nickname', sa.String(length=255), nullable=False, comment='用户昵称'),
    sa.Column('user_type', sa.Integer(), nullable=False, comment='用户类型 10 管理人员, 20 测试人员'),
    sa.Column('remarks', sa.String(length=255), nullable=False, comment='用户描述'),
    sa.Column('avatar', sa.Text(), nullable=False, comment='头像'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('user_login_record',
    sa.Column('token', sa.String(length=40), nullable=True, comment='登陆token'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='账号'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='用户名称'),
    sa.Column('logout_type', sa.String(length=50), nullable=True, comment='退出类型'),
    sa.Column('login_type', sa.String(length=50), nullable=True, comment='登陆方式   扫码  账号密码等'),
    sa.Column('login_time', sa.DateTime(), nullable=True, comment='登陆时间'),
    sa.Column('logout_time', sa.DateTime(), nullable=True, comment='退出时间'),
    sa.Column('login_ip', sa.String(length=30), nullable=True, comment='登录IP'),
    sa.Column('ret_msg', sa.String(length=255), nullable=True, comment='返回信息'),
    sa.Column('ret_code', sa.String(length=9), nullable=True, comment='是否登陆成功  返回状态码  0成功'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('source_type', sa.String(length=255), nullable=True, comment='来源'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_record_code_logintime', 'user_login_record', ['code', 'login_time'], unique=False)
    op.create_index(op.f('ix_user_login_record_code'), 'user_login_record', ['code'], unique=False)
    op.create_index(op.f('ix_user_login_record_login_ip'), 'user_login_record', ['login_ip'], unique=False)
    op.create_index(op.f('ix_user_login_record_login_time'), 'user_login_record', ['login_time'], unique=False)
    op.create_index(op.f('ix_user_login_record_login_type'), 'user_login_record', ['login_type'], unique=False)
    op.create_index(op.f('ix_user_login_record_ret_code'), 'user_login_record', ['ret_code'], unique=False)
    op.create_index(op.f('ix_user_login_record_token'), 'user_login_record', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_login_record_token'), table_name='user_login_record')
    op.drop_index(op.f('ix_user_login_record_ret_code'), table_name='user_login_record')
    op.drop_index(op.f('ix_user_login_record_login_type'), table_name='user_login_record')
    op.drop_index(op.f('ix_user_login_record_login_time'), table_name='user_login_record')
    op.drop_index(op.f('ix_user_login_record_login_ip'), table_name='user_login_record')
    op.drop_index(op.f('ix_user_login_record_code'), table_name='user_login_record')
    op.drop_index('idx_login_record_code_logintime', table_name='user_login_record')
    op.drop_table('user_login_record')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_roles_role_type'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_menus'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('request_history')
    op.drop_table('project_info')
    op.drop_index(op.f('ix_notify_user_id'), table_name='notify')
    op.drop_table('notify')
    op.drop_table('module_info')
    op.drop_index(op.f('ix_menu_view_history_user_id'), table_name='menu_view_history')
    op.drop_index(op.f('ix_menu_view_history_remote_addr'), table_name='menu_view_history')
    op.drop_index(op.f('ix_menu_view_history_menu_id'), table_name='menu_view_history')
    op.drop_table('menu_view_history')
    op.drop_index(op.f('ix_menu_title'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_index(op.f('ix_menu_icon'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_lookup_value_lookup_id'), table_name='lookup_value')
    op.drop_index(op.f('ix_lookup_value_lookup_code'), table_name='lookup_value')
    op.drop_table('lookup_value')
    op.drop_index(op.f('ix_lookup_code'), table_name='lookup')
    op.drop_table('lookup')
    op.drop_index(op.f('ix_file_info_extend_name'), table_name='file_info')
    op.drop_table('file_info')
    op.drop_table('celery_periodic_task_changed')
    op.drop_table('celery_periodic_task')
    op.drop_table('celery_interval_schedule')
    op.drop_table('celery_crontab_schedule')
    # ### end Alembic commands ###
