"""
常量定义
"""

# 响应状态码
SUCCESS_CODE = 200
ERROR_CODE = 500

# 缓存键前缀
CACHE_PREFIX_USER = "user:"
CACHE_PREFIX_ROLE = "role:"
CACHE_PREFIX_PERMISSION = "permission:"
CACHE_PREFIX_MENU = "menu:"

# 缓存过期时间（秒）
CACHE_EXPIRE_USER = 3600  # 1小时
CACHE_EXPIRE_ROLE = 3600  # 1小时
CACHE_EXPIRE_PERMISSION = 3600  # 1小时
CACHE_EXPIRE_MENU = 3600  # 1小时

# Token相关
TOKEN_EXPIRE_MINUTES = 60 * 24  # 24小时
REFRESH_TOKEN_EXPIRE_DAYS = 7  # 7天

# 密码相关
PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 20

# 分页相关
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
